name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Poetry
      run: |
        curl -fsS https://install.python-poetry.org | python - -y
    - name: Update PATH
      if: ${{ runner.os != 'Windows' }}
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Update PATH for Windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install
    - name: Build
      run: |
        poetry run maturin build
        poetry run maturin develop
    - name: Run tests
      run: |
        poetry run python example.py
