name: Build and test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      shell: bash
      run: |
        python3 -m venv .env
        source .env/bin/activate
        pip install maturin
    - name: Build
      shell: bash
      run: |
        maturin develop
    - name: Run tests
      shell: bash
      run: |
        python3 example.py
  
